/**
 * On-demand preamble sections.
 *
 * One-time onboarding flows (routing-rules offer, first-run guidance, vendored
 * copy warning, the writing-style / proactive / Boil-the-Ocean prompts) only
 * fire when a preamble echo value says so. After onboarding, which is the
 * normal state, none of them fire, yet their ~8KB of prose used to ship inline
 * in every SKILL.md and be read on every skill run.
 *
 * Same split as the {{SECTION:id}} resolver (sections.ts):
 *  - On CLAUDE: the section renders as ONE gate line pointing at a generated
 *    file, `{skillRoot}/preamble/sections/<id>.md`, read only when the gate
 *    holds. gen-skill-docs writes those files (and freshness-checks them).
 *  - On every OTHER host: the section inlines exactly as before, so there is
 *    no host-portable-path problem.
 *
 * Each gate is the section's own trigger condition, restated verbatim from its
 * body, over values the preamble probe (bin/paysec-preamble) prints.
 */
import type { TemplateContext } from '../types';
import { generateFirstRunGuidance } from './generate-first-run-guidance';
import { generateRoutingInjection } from './generate-routing-injection';
import { generateVendoringDeprecation } from './generate-vendoring-deprecation';
import { generateProactivePrompt } from './generate-proactive-prompt';
import { generateLakeIntro } from './generate-lake-intro';
import { generateWritingStyleMigration } from './generate-writing-style-migration';

export interface OnDemandSection {
  id: string;
  /** Markdown condition over preamble echo values; the file is read only when true. */
  gate: string;
  render: (ctx: TemplateContext) => string;
}

export const ON_DEMAND_SECTIONS: OnDemandSection[] = [
  { id: 'writing-style-migration', gate: '`WRITING_STYLE_PENDING` is `yes`', render: generateWritingStyleMigration },
  { id: 'lake-intro', gate: '`LAKE_INTRO` is `no`', render: () => generateLakeIntro() },
  { id: 'proactive-prompt', gate: '`PROACTIVE_PROMPTED` is `no` AND `TEL_PROMPTED` is `yes`', render: generateProactivePrompt },
  { id: 'first-run-guidance', gate: '`ACTIVATED` is `no` OR `FIRST_LOOP_SHOWN` is `no`', render: generateFirstRunGuidance },
  { id: 'routing-injection', gate: '`HAS_ROUTING` is `no` AND `ROUTING_DECLINED` is `false` AND `PROACTIVE_PROMPTED` is `yes`', render: generateRoutingInjection },
  { id: 'vendoring-deprecation', gate: '`VENDORED_PAYSEC` is `yes`', render: generateVendoringDeprecation },
];

function find(id: string): OnDemandSection {
  const s = ON_DEMAND_SECTIONS.find(x => x.id === id);
  if (!s) throw new Error(`unknown on-demand preamble section: ${id}`);
  return s;
}

/** Published path of an on-demand section file, relative to the skill root. */
export function onDemandSectionRelPath(id: string): string {
  return `preamble/sections/${id}.md`;
}

/**
 * The text a skill's preamble carries for this section: a gate pointer on
 * Claude, the full inline body on other hosts. A leading `## ` heading stays
 * inline so the section index a reader skims is unchanged.
 */
export function renderOnDemand(ctx: TemplateContext, id: string): string {
  const s = find(id);
  const body = s.render(ctx);
  if (ctx.host !== 'claude') return body;
  const heading = body.startsWith('## ') ? body.slice(0, body.indexOf('\n')) + '\n\n' : '';
  return `${heading}If ${s.gate}: Read \`${ctx.paths.skillRoot}/${onDemandSectionRelPath(id)}\` and follow it. Otherwise skip it.`;
}

/** Content of the generated on-demand file (Claude host). */
export function renderOnDemandFile(ctx: TemplateContext, id: string): string {
  return `<!-- AUTO-GENERATED by scripts/gen-skill-docs.ts from scripts/resolvers/preamble/on-demand.ts — do not edit directly -->\n<!-- Regenerate: bun run gen:skill-docs -->\n\n${find(id).render(ctx)}\n`;
}
